# Generated by Django 4.2 on 2023-04-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_teamassignment_user_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamassignment",
            name="can_add_teammate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teamassignment",
            name="can_remove_teammate",
            field=models.BooleanField(default=True),
        ),
    ]
