# Generated by Django 4.2 on 2023-04-09 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_schemaviewerassignment_schema_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="schema",
            new_name="schemas",
        ),
    ]
