# Generated by Django 4.2 on 2023-04-04 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0002_remove_snippet_editor_remove_snippet_viewer"),
        ("accounts", "0003_teamassignment_can_add_teammate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_add_viewer", models.BooleanField(default=True)),
                ("can_remove_viewer", models.BooleanField(default=True)),
                (
                    "snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snippets.snippet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_add_editor", models.BooleanField(default=True)),
                ("can_remove_editor", models.BooleanField(default=True)),
                (
                    "snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snippets.snippet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="editor",
            field=models.ManyToManyField(
                related_name="with_editor_access",
                through="accounts.EditorAssignment",
                to="snippets.snippet",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="viewer",
            field=models.ManyToManyField(
                related_name="with_viewer_access",
                through="accounts.ViewerAssignment",
                to="snippets.snippet",
            ),
        ),
    ]
