# Generated by Django 4.2 on 2023-04-05 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0001_initial"),
        ("accounts", "0004_viewerassignment_editorassignment_user_editor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="editor",
            new_name="snippet_editor",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="viewer",
            new_name="snippet_viewer",
        ),
        migrations.CreateModel(
            name="SchemaViewerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_add_viewer", models.BooleanField(default=True)),
                ("can_remove_viewer", models.BooleanField(default=True)),
                (
                    "snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schema.schema"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchemaEditorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_add_editor", models.BooleanField(default=True)),
                ("can_remove_editor", models.BooleanField(default=True)),
                (
                    "snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schema.schema"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="schema_editor",
            field=models.ManyToManyField(
                related_name="with_editor_access",
                through="accounts.SchemaEditorAssignment",
                to="schema.schema",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="schema_viewer",
            field=models.ManyToManyField(
                related_name="with_viewer_access",
                through="accounts.SchemaViewerAssignment",
                to="schema.schema",
            ),
        ),
    ]
