# Generated by Django 4.2 on 2023-04-07 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_rename_editor_user_snippet_editor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schemaeditorassignment",
            old_name="snippet",
            new_name="schema",
        ),
        migrations.RenameField(
            model_name="schemaviewerassignment",
            old_name="snippet",
            new_name="schema",
        ),
    ]
