# Generated by Django 4.2 on 2023-04-04 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snippet",
            name="editor",
        ),
        migrations.RemoveField(
            model_name="snippet",
            name="viewer",
        ),
    ]
