# Generated by Django 4.2 on 2023-04-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0002_remove_snippet_editor_remove_snippet_viewer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
