# Generated by Django 4.2 on 2023-04-05 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0003_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="snippets.folder",
            ),
        ),
    ]
