# Generated by Django 4.2 on 2023-04-07 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0004_snippet_folder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snippet",
            name="folder",
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
    ]
