# Generated by Django 4.2 on 2023-04-05 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0002_folder_schema_folder"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("url", models.URLField()),
                ("host", models.CharField(max_length=250)),
                ("port", models.CharField(max_length=250)),
                ("database_name", models.CharField(max_length=250)),
                ("username", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
                ("use_ssl", models.BooleanField(default=False)),
                ("use_ssl_tunnel", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="schema",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="schema.datasource",
            ),
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
    ]
