# Generated by Django 4.2 on 2023-04-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0003_datasource_alter_schema_folder_delete_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="category",
            field=models.CharField(
                choices=[
                    ("PostgreSQL", "PostgreSQL"),
                    ("MySQL", "MySQL"),
                    ("Amazon Redshift", "Amazon Redshift"),
                    ("Big Query", "Big Query"),
                    ("Snowflake", "Snowflake"),
                    ("Excel", "Excel"),
                    ("CSV", "CSV"),
                ],
                default="Undefined",
                max_length=255,
            ),
        ),
    ]
