# Generated by Django 4.2 on 2023-04-07 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0004_datasource_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schema",
            old_name="folder",
            new_name="datasource",
        ),
    ]
