# Generated by Django 4.2 on 2023-04-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0005_rename_folder_schema_datasource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="category",
            field=models.CharField(
                choices=[
                    ("PostgreSQL", "PostgreSQL"),
                    ("MySQL", "MySQL"),
                    ("Amazon Redshift", "Amazon Redshift"),
                    ("Microsoft SQL Server", "Microsoft SQL Server"),
                    ("Oracle", "Oracle"),
                    ("Excel", "Excel"),
                    ("CSV", "CSV"),
                ],
                default="Undefined",
                max_length=255,
            ),
        ),
    ]
